# Generated by Django 4.0 on 2021-12-23 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('telegram_id', models.PositiveIntegerField(unique=True, verbose_name='AGENT IDsi')),
                ('name', models.CharField(default='name', max_length=400, verbose_name='AGENT ISMI')),
                ('tel_num', models.CharField(default='+998912345678', max_length=50, verbose_name='AGENT TELEFON RAQAMI')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('charecter', models.TextField(verbose_name='MAXSULOT XAQIDA')),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='images', verbose_name='RASM')),
                ('narx', models.IntegerField(verbose_name='NARXI')),
                ('name', models.CharField(default='name', max_length=100, verbose_name='MAXSULOT NOMI')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('money', models.PositiveIntegerField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('refused', models.BooleanField(blank=True, default=False, null=True)),
                ('client_name', models.CharField(default=None, max_length=300)),
                ('client_number', models.CharField(default=None, max_length=15)),
                ('client_addres', models.TextField(default=None)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.agent')),
                ('to_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all.product')),
            ],
        ),
    ]
